[package]
name = 'candymachine'
version = '1.0.0'

[addresses]
candymachine = "0x5e82826266ac639ba5c87a621cba724d7752cfc95d02043f425a261451c2c4a6"
Std = "0x1"
aptos_std = "0x1"

[dependencies]
AptosFramework = { local = "../../../../aptos-core/aptos-move/framework/aptos-framework"}
AptosToken = { local = "../../../../aptos-core/aptos-move/framework/aptos-token" }
AptosStdlib = { local = "../../../../aptos-core/aptos-move/framework/aptos-stdlib" }
DataStructure = { local = "../../../../aptos-core/aptos-move/move-examples/data_structures" }
